web:
    build: .
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    links:
        - db
    ports:
        - "3000:3000"
    volumes:
        - .:/app
    volumes_from:
        - bundle

db:
    image: postgres
    ports:
        - "5432"

bundle:
    image: dockerrailsstarter_web
    command: echo This is the bundle volume image
    volumes:
        - /bundle
